#! /bin/sh
# 
#
# 
#  _                                  
# | |__  ___ _ ____      ___ __ ___   
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \  
# | |_) \__ \ |_) \ V  V /| | | | | | 
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_| 
#           |_|                       
#                A U T O S T A R T   
#
#
#
############# Configuration #############
#bspc monitor -d            
bspc monitor -d I II III IV V VI VII VIII IX X

############# Set Compose Key to R-Alt #############
setxkbmap -option compose:ralt &

############# xfce settings  #############
#xfsettingsd &

############# Common BSPWM Configuration  #############
bspc config border_width        	2
bspc config window_gap         		8
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false
bspc config focus_follows_pointer 	true
bspc config top_padding 			34
bspc config bottom_padding 			34

############# Color Settings #############
# source the colors.
"${HOME}/.cache/wal/colors.sh"
# Set the border colors. (from PyWal)
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color3"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
bspc config  format-foreground "$color9"

############# Use Mouse to resize, move Window #############
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

##################
## window rules ##
##################

############# Workspace 1 ( system) #############
bspc rule -a htop desktop='^1' follow=on focus=on
bspc rule -a fslint-gui desktop='^1' follow=on focus=on
bspc rule -a Lxappearance desktop='^1' state=floating follow=on
bspc rule -a Lightdm-gtk-greeter-settings desktop='^1' state=floating follow=on
bspc rule -a System-config-printer.py desktop='^1' state=floating follow=on
bspc rule -a Pavucontrol desktop='^1' state=floating follow=on
bspc rule -a Exo-helper-1 desktop='^1' state=floating follow=on
bspc rule -a Lxrandr desktop='^1' state=floating follow=on
bspc rule -a Arandr desktop='^1' state=floating follow=on
bspc rule -a luckybackup desktop='^1' state=floating follow=on
bspc rule -a grsync desktop='^1' state=floating follow=on

#############  Workspace 2 ( Browser) #############
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on

############# Workspace 3 (  File) #############
bspc rule -a Filezilla desktop='^3' state=floating follow=on
bspc rule -a Thunar desktop='^3' follow=on focus=on

############# Workspace 4 ( text-processing) #############
bspc rule -a libreoffice-startcenter desktop='^4' state=floating follow=on
bspc rule -a libreoffice desktop='^4' follow=on focus=on
bspc rule -a libreoffice-base desktop='^4' follow=on focus=on

############# Workspace 5 ( graphics-utilities) #############
bspc rule -a Viewnior desktop='^5' state=floating follow=on
bspc rule -a Gimp-2.10 desktop='^5' follow=on focus=on
bspc rule -a Inkscape desktop='^5' follow=on focus=on
bspc rule -a Oomox desktop='^5' follow=on focus=on

############# Workspace 6 ( videocasting) #############
bspc rule -a kazam desktop='^6' follow=on focus=on
bspc rule -a obs desktop='^6' follow=on focus=on
bspc rule -a simplescreenrecorder desktop='^6' follow=on focus=on

############# Workspace 7 ( music-voice) #############
bspc rule -a Audacity desktop='^7' follow=on focus=on
bspc rule -a deepin-voice-recorder desktop='^7' follow=on focus=on

############# Workspace 8 ( programming) #############
bspc rule -a Geany desktop='^8' follow=on focus=on
bspc rule -a VirtualBox desktop='^8' state=floating follow=on

############# Workspace 9 ( communications) #############
#bspc rule -a Thunderbird desktop='^9' follow=on focus=on
#bspc rule -a Evolution desktop='^9' follow=on focus=on
bspc rule -a Claws-mail desktop='^9' follow=on focus=on

############# Workspace 10 ( Presentations) #############
bspc rule -a calibre desktop='^10' follow=on focus=on
bspc rule -a Celluloid desktop='^10' state=floating follow=on

############# pseudo tiled rules #############
bspc rule -a Skype            pseudo_tiled=on focus=on
bspc rule -a File-roller      pseudo_tiled=on focus=on
bspc rule -a Transmission-gtk pseudo_tiled=on focus=on
bspc rule -a catfish 		  pseudo_tiled=on focus=on

############# need to be floating #############
bspc rule -a Gnome-mpv state=floating follow=on focus=on
bspc rule -a Xfce4-terminal state=floating follow=on focus=on
bspc rule -a Orage state=floating follow=on focus=on
bspc rule -a rofi state=floating follow=on focus=on
bspc rule -a Mousepad state=floating follow=on focus=on
bspc rule -a Agave state=floating follow=on focus=on
bspc rule -a '*:yad' state=floating follow=on focus=on

###############
## autostart ##
###############

############# Load bitmap fonts #############
xset fp+ ~/.local/share/fonts &

############# Compositor #############
pkill picom
picom -b &

############# network applet #############
nm-applet &

############# volume icon #############
pkill volumeicon
volumeicon &

############# keybind daemon #############
pkill sxhkd
	sxhkd &

############# reload the xsettingsd, a minimal x settings daemon #############
pkill xsettingsd
	xsettingsd &

############# load notifier #############
pkill xfce4-notifyd
	xfce4-notifyd &

############# reload the cursor theme #############
xsetroot -cursor_name left_ptr

############# Panel(s) #############
pkill polybar
	~/.config/polybar/launch.sh &
pkill tint2
	tint2 &

############# Dropbox #############
pkill dropbox
	dropbox start &
	
############# Screensaver-locker #############
pkill light-locker
	light-locker &
#pkill xfce4-screensaver
#	xfce4-screensaver &

############# Conky #############
pkill conky
	~/.conky/OBconky-startup.sh &
	
############# policykit-1-gnome #############
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

############# lxpolkit #############
#lxpolkit &

############# Power Management Items #############
thermald &
xfce4-power-manager &
tlp start &
#indicator-cpufreq &
powertop --auto-tune &

############# Redshift #############
redshift-gtk &

############# Touchpad Indicator #############
touchpad-indicator &

############# MX Brightness Controller #############
#/usr/share/brightness-controller/init.py

start-pulseaudio-11 &

############# set random wallpaper ############# 

feh --randomize --bg-fill /usr/share/backgrounds/wallpapers/* &

hibernator &
